server:
  port: 10010
spring:
  application:
    name: leyou-gateway
eureka:
  client:
    registry-fetch-interval-seconds: 5
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
zuul:
  prefix: /api # 路由路径前缀
  retryable: true # 商品微服务的映射路径
  routes:
      item-service: /item/**
      search-service: /search/**
      user-service: /user/**

ribbon:
  connectionTimeout: 1000
  readTimeout: 1000

